server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${ChunXi.datasource.driver-class-name}
      url: jdbc:mysql://${ChunXi.datasource.host}:${ChunXi.datasource.port}/${ChunXi.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${ChunXi.datasource.username}
      password: ${ChunXi.datasource.password}
  redis:
    host: ${ChunXi.redis.host}
    port: ${ChunXi.redis.port}
    password: ${ChunXi.redis.password}
    database: ${ChunXi.redis.database}
  wechat:
    appid: ${ChunXi.wechat.appid}
    secret: ${ChunXi.wechat.secret}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ChunXi.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

chunxi:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ChunXi
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: Dennis
    user-ttl: 7200000
    user-token-name: authentication

  alioss:
    endpoint: ${endpoint}
    access-key-id: ${access-ke-id}
    access-key-secret: ${access-key-secret}
    bucket-name: ${bucket-name}
  wechat:
    appid: ${Chunxi.wechat.appid}
    secret: ${Chunxi.wechat.secret}
    mchid: ${Chunxi.wechat.mchid}
    mchSerialNo: ${Chunxi.wechat.mchSerialNo}
    privateKeyFilePath: ${Chunxi.wechat.privateKeyFilePath}
    apiV3Key: ${Chunxi.wechat.apiV3Key}
    weChatPayCertFilePath: ${Chunxi.wechat.weChatPayCertFilePath}
    notifyUrl: ${Chunxi.wechat.notifyUrl}
    refundNotifyUrl: ${Chunxi.wechat.refundNotifyUrl}

  shop:
    address: 无锡市滨湖区钱荣路86号
  baidu:
    ak: vpSDndeptSLIL1GrIGv8a3La3MSUMIvG

