ChunXi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 152.67.231.250
    port: 3306
    database: Rst_Haruhiro
    username: root
    password: lijunhaha
  alioss:
    endpoint: oss-rg-china-mainland.aliyuncs.com
    access-key-id: LTAI5tBmT8iHs9x3GeGP5kha

    access-key-secret: N3DVG4sBrRhFB6FFuIZ3wgFr3YXKWf
    bucket-name: harohiro