ChunXi:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 152.67.231.250
    port: 3306
    database: Rst_Haruhiro
    username: root
    password: lijunhaha
  alioss:
    endpoint: oss-rg-china-mainland.aliyuncs.com
    access-key-id: LTAI5tBmT8iHs9x3GeGP5kha
    access-key-secret: N3DVG4sBrRhFB6FFuIZ3wgFr3YXKWf
    bucket-name: harohiro
  redis:
    host: 152.67.231.250
    port: 6379
    password: root1234
    database: 10
  wechat:
    appid: wx9a88e898fab66cc2
    secret: e44423a91f56294580cbe991feacbb60
#########################################################################
# 微信支付相关配置，
#    appid: wxcd2e39f677fd30ba
#    secret: 84fbfdf5ea288f0c432d829599083637
#    mchid: 1561414331
#    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
#    privateKeyFilePath: D:\apiclient_key.pem
#    apiV3Key: CZBK51236435wxpay435434323FFDuv3
#    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
#    notifyUrl: https://www.weixin.qq.com/wxpay/pay.php
#    refundNotifyUrl: https://www.weixin.qq.com/wxpay/pay.php